### PR TITLE
Fix no word wrap bug - fixes #18

### LINKED ISSUE #18: Setting wordWrap to false does not always result in correct wrapping
With the following piece of text as input

> 12345678\n901234567890 12345

And, setting `wordWrap` to false with a character count of `5` currently results in the following output

> 12345678
> 901234567890
> 12345

The reason for this is that [this line](https://github.com/chalk/wrap-ansi/blob/master/index.js#L134)  does not take the `wordWrap` setting into account.

Fix is coming up!

### PR DESCRIPTION
**Pull request by SamVerschueren**
Apparently this use case was missed when I implemented the `wordWrap` option.

This one is also needed in order to solve PR #17 entirely.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -131,6 +131,11 @@ function exec(str, cols, opts) {
 			rows.push('');
 		}
 
+		if (options.wordWrap === false) {
```
Comment (SamVerschueren) [inline index.js]: I think I can optimise this by only executing `wrapWord` when the total length would exceed the number of columns. Otherwise we can just append.
